spring:
  profiles: prod
  jackson:
    serialization.INDENT_OUTPUT: true

# Actuator configuration
management:
  endpoint:
    health:
      show-details: always
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    encoding: "@project.build.sourceEncoding@"
    java.version: "@java.version@"